export { default as Navbar} from "./Navbar/Navbar"
export { default as Hero } from "./Hero/Hero"
export { default as Hero2 } from "./Hero/Hero2"
export { default as OurServices } from "./OurService/OurService"
export { default as WhyChooseUs } from "./WhyChooseUs/WhyChooseUs"
export { default as HowItWorks } from "./HowItWorks/HowItWorks"